;  Character ROM mappings

CHARACTER_DATA_L:
  .byte $00	; SPACE
  .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
  .byte $00	; SPACE
  .byte $04	; !
  .byte $00	; "
  .byte $53	; #
  .byte $93	; $
  .byte $a0	; %
  .byte $90	; &
  .byte $00	; '
  .byte $21	; (
  .byte $24	; )
  .byte $4a	; *
  .byte $e4	; +
  .byte $e0	; ,
  .byte $08	; -
  .byte $48	; .
  .byte $ae	; /
  .byte $4e	; 0
  .byte $4e	; 1
  .byte $2e	; 2
  .byte $e2	; 3
  .byte $4e	; 4
  .byte $ee	; 5
  .byte $22	; 6
  .byte $ae	; 7
  .byte $e2	; 8
  .byte $08	; 9
  .byte $04	; :
  .byte $08	; ;
  .byte $84	; <
  .byte $0e	; =
  .byte $48	; >
  .byte $48	; ?
  .byte $84	; @
  .byte $ea	; A
  .byte $ae	; B
  .byte $8e	; C
  .byte $ae	; D
  .byte $8e	; E
  .byte $c8	; F
  .byte $ae	; G
  .byte $ea	; H
  .byte $4e	; I
  .byte $4c	; J
  .byte $ca	; K
  .byte $8e	; L
  .byte $aa	; M
  .byte $aa	; N
  .byte $a4	; O
  .byte $e8	; P
  .byte $e2	; Q
  .byte $ca	; R
  .byte $2e	; S
  .byte $44	; T
  .byte $ae	; U
  .byte $a4	; V
  .byte $ee	; W
  .byte $aa	; X
  .byte $44	; Y
  .byte $8e	; Z
  .byte $46	; [
  .byte $20	; \
  .byte $26	; ]
  .byte $00	; ^
  .byte $07	; _
  .byte $08	; `
  .byte $ea	; A
  .byte $ae	; B
  .byte $8e	; C
  .byte $ae	; D
  .byte $8e	; E
  .byte $c8	; F
  .byte $ae	; G
  .byte $ea	; H
  .byte $4e	; I
  .byte $4c	; J
  .byte $ca	; K
  .byte $8e	; L
  .byte $aa	; M
  .byte $aa	; N
  .byte $a4	; O
  .byte $e8	; P
  .byte $e2	; Q
  .byte $ca	; R
  .byte $2e	; S
  .byte $44	; T
  .byte $ae	; U
  .byte $a4	; V
  .byte $ee	; W
  .byte $aa	; X
  .byte $44	; Y
  .byte $8e	; Z

CHARACTER_DATA_H:
  .byte $00	; SPACE
  .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
  .byte $00	; SPACE
  .byte $44	; !
  .byte $90	; "
  .byte $36	; #
  .byte $1b	; $
  .byte $a1	; %
  .byte $93	; &
  .byte $28	; '
  .byte $12	; (
  .byte $42	; )
  .byte $0a	; *
  .byte $04	; +
  .byte $00	; ,
  .byte $00	; -
  .byte $02	; .
  .byte $ea	; /
  .byte $c4	; 0
  .byte $e6	; 1
  .byte $e6	; 2
  .byte $aa	; 3
  .byte $ec	; 4
  .byte $e8	; 5
  .byte $e2	; 6
  .byte $ee	; 7
  .byte $ea	; 8
  .byte $08	; 9
  .byte $04	; :
  .byte $04	; ;
  .byte $04	; <
  .byte $0e	; =
  .byte $09	; >
  .byte $c5	; ?
  .byte $8c	; @
  .byte $4a	; A
  .byte $8e	; B
  .byte $e	; C
  .byte $2e	; D
  .byte $ec	; E
  .byte $e8	; F
  .byte $e8	; G
  .byte $88	; H
  .byte $e4	; I
  .byte $e4	; J
  .byte $8a	; K
  .byte $88	; L
  .byte $ee	; M
  .byte $ca	; N
  .byte $4a	; O
  .byte $ea	; P
  .byte $ea	; Q
  .byte $ca	; R
  .byte $ec	; S
  .byte $e4	; T
  .byte $aa	; U
  .byte $aa	; V
  .byte $aa	; W
  .byte $a4	; X
  .byte $a4	; Y
  .byte $e4	; Z
  .byte $64	; [
  .byte $84	; \
  .byte $62	; ]
  .byte $25	; ^
  .byte $00	; _
  .byte $42	; `
  .byte $4a	; A
  .byte $8e	; B
  .byte $e	; C
  .byte $2e	; D
  .byte $ec	; E
  .byte $e8	; F
  .byte $e8	; G
  .byte $88	; H
  .byte $e4	; I
  .byte $e4	; J
  .byte $8a	; K
  .byte $88	; L
  .byte $ee	; M
  .byte $ca	; N
  .byte $4a	; O
  .byte $ea	; P
  .byte $ea	; Q
  .byte $ca	; R
  .byte $ec	; S
  .byte $e4	; T
  .byte $aa	; U
  .byte $aa	; V
  .byte $aa	; W
  .byte $a4	; X
  .byte $a4	; Y
  .byte $e4	; Z
