out_file = open("a.rom", "wb")
for x in range(2048):
    out_file.write(int("0x00", 0).to_bytes(1, 'little'))
    out_file.write(int("0x00", 0).to_bytes(1, 'little'))
    out_file.write(int("0x38", 0).to_bytes(1, 'little'))
    out_file.write(int("0x6c", 0).to_bytes(1, 'little'))
    out_file.write(int("0xc6", 0).to_bytes(1, 'little'))
    out_file.write(int("0xc6", 0).to_bytes(1, 'little'))
    out_file.write(int("0xc6", 0).to_bytes(1, 'little'))
    out_file.write(int("0xfe", 0).to_bytes(1, 'little'))
    out_file.write(int("0xc6", 0).to_bytes(1, 'little'))
    out_file.write(int("0xc6", 0).to_bytes(1, 'little'))
    out_file.write(int("0xc6", 0).to_bytes(1, 'little'))
    out_file.write(int("0xc6", 0).to_bytes(1, 'little'))
    out_file.write(int("0x00", 0).to_bytes(1, 'little'))
    out_file.write(int("0x00", 0).to_bytes(1, 'little'))
    out_file.write(int("0x00", 0).to_bytes(1, 'little'))
    out_file.write(int("0x00", 0).to_bytes(1, 'little'))
